version: '3'

services:
  db:
    container_name: postgres
    image: postgres
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_DB}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    command: ['postgres', '-c', 'listen_addresses=*']

volumes:
  pgdata:
